### PR TITLE
DBDAART-7483 - Added set_as_null function to TAF_Closure.py

### PR DESCRIPTION
**Pull request by a-pfeiffer**
## What is this and why are we doing it?
This change is to create a global function to set a field to null.

* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-####
https://jiraent.cms.gov/browse/DBDAART-7438

## What are the security implications from this change?
N/A

## How did I test this?
before/after sqls with test usage attached to the ticket.

## Should there be new or updated documentation for this change? (Be specific.)
No

## PR Checklist
- [x ] The JIRA ticket number and a short description is in the subject line
- [ x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ n/a] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by XiaoBarry** [comment]
@a-pfeiffer it looks good. Just one comment, do we need to declare the parameter alias in the new set_as_null function? Unlike other cleanser function, we don't need alias to set deprecated variables as null. Would be better to remove it?

**Review by XiaoBarry — APPROVED** [review]

**Comment by a-pfeiffer** [comment]
Hi @alihashmi-wh hoping you can take a look at this PR, please let me know if you have any questions about it!

**Comment by alihashmi-wh** [comment]
Hi @a-pfeiffer, sorry for the delay. I have taken a look at the PR and things look good for the most part. I feel it would be worthwhile to either remove `alias` as a function parameter, or use it in the function body. Perhaps we can set up some time to chat about the background, so that I could better understand the intent. Thanks!

**Comment by a-pfeiffer** [comment]
Hi @alihashmi-wh I added a comment regarding requiring the parameter but not using it to the function.   I added the resulting sql to the ticket.   Please review and let me know if you have any concerns!

**Review by alihashmi-wh — APPROVED** [review]
Looks good, @a-pfeiffer! Thank you for adding the clarification.

**Review by XiaoBarry — APPROVED** [review]
Thanks @a-pfeiffer! It looks good.

**Pull request merged**
