### PR TITLE
DBDAART-5011 Update CODEOWNERS to remove DC members

### PR DESCRIPTION
**Pull request by C1KB-tensileai**
## What is this and why are we doing it?
Earlier this month, we cut-over production of TAF to the DataConnect platform. Now that the run has completed, we need to refine the individuals responsible for maintaining the ETL contained in this repository. 

* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-5011

## What are the security implications from this change?
This change does not introduce any new security implications.

## How did I test this?
I confirmed my changes to `CODEOWNERS` were syntactically correct in the branch's commit history.

## Should there be new or updated documentation for this change? (Be specific.)
I don't think any specific documentation is needed for this change, as the contents of the `CODEOWNERS` file should be sufficient.

## PR Checklist
- [x] The JIRA ticket number and a short description is in the subject line
- [x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by TUAS-forpeople — APPROVED** [review]

**Review by VPAI-Bixal — DISMISSED** [review]

**Comment by C1KB-tensileai** [comment]
@a-pfeiffer FYI, not sure I should merge this since there are several feature branches for CCB changes?

**Comment by TUAS-forpeople** [comment]
What's going on with this PR. I would certainly like to no longer be in the CODEOWNERS.

**Comment by a-pfeiffer** [comment]
@C1KB-tensileai Scott, I am good with you merging this in when you see fit.

**Review by AX2J-Bixal — DISMISSED** [review]

**Review by TUAS-forpeople — APPROVED** [review]

**Review by VPAI-Bixal — DISMISSED** [review]

**Review by TUAS-forpeople — CHANGES_REQUESTED** [review]
It looks like the contents should be:
`@a-pfeiffer @alihashmi-wh @XiaoBarry @fumanjie @hls0231`

**Review by TUAS-forpeople — APPROVED** [review]

**Review by VPAI-Bixal — APPROVED** [review]

**Review by AX2J-Bixal — APPROVED** [review]

**Pull request merged**
