### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pkui-cmcs**
## What is this?
Fix for reg_flag issue, changed st_abbrev in BSF_Metadata.py to include AK, CA, NC, TX, WY
## How would you classify this change (feature, bug, maintenance, etc.)?
maintenance
## Is there accompanying documentation for this change?
No
## Issues Encountered

*Optional section to include any challenges encountered, options considered, and the approach chosen.*

## PR Checklist
- [ ] Is the issue number and a short description in the subject line?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

_Credit to TMSIS PR template and https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects_

### CODE REVIEW

**Comment by C1KB-tensileai** [comment]
Looks good, I resolved a conflict with CODEOWNERS to align with main/master.

**Review by C1KB-tensileai — COMMENTED** [review]
Resolved a conflict with CODEOWNERS to align with main/master

**Review by C1KB-tensileai — APPROVED** [review]

**Comment by C1KB-tensileai** [comment]
Looks good, thanks Edwin

**Comment by alihashmi-wh** [comment]
tagging this commit to jira issue: MACDC-3979

**Pull request merged**
