### PR TITLE
DBDAART-6766 - Updated subData to include a line to declare Nebraska …

### PR DESCRIPTION
**Pull request by a-pfeiffer**
…(State 31) Elig file (ELG) as CSO effective 2024-02-02, with placeholder end date.

## What is this and why are we doing it?
Nebraska changing their Elig Submission Type, this change is to accomodate that.

* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-####

## What are the security implications from this change?
None known

## How did I test this?
I created a version of the function with the change, ran the function and viewed the results, confirmed they are as expected.

## Should there be new or updated documentation for this change? (Be specific.)
Will Inquire, seems possible. 

## PR Checklist
- [x] The JIRA ticket number and a short description is in the subject line
- [x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by a-pfeiffer** [comment]
Testing notebook here:
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1431816658108416

**Review by C1KB-tensileai — APPROVED** [review]
I compared with the corresponding SQL to update production (Redshift) and agree with this change.

**Comment by C1KB-tensileai** [comment]
@a-pfeiffer I do not believe there's any documentation on CSO submitters (at least on DC's end) to update.

**Review by XiaoBarry — APPROVED** [review]
I compared this code change with script/result in Redshift. It looks good!

**Pull request merged**
