### PR TITLE
Dbdaart 7257   rx  deprecate copay waived ind data element

### PR DESCRIPTION
**Pull request by a-pfeiffer**
## What is this and why are we doing it?
CCB ticket calls for this field to be deprecated/set to null.  Leveraged TAF_Closure.set_as_null to set COPAY WAIVED IND to null upon extraction from T-MSIS, and var_set_type data cleaning function for this field in creation of view RXH.

* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-####
https://jiraent.cms.gov/browse/DBDAART-7257

## What are the security implications from this change?
N/A

## How did I test this?
Visually examined the sql.   Ran TAF for test month/state before and after change, and compared all values before and after change.   All differences found in testing were expected.

## Should there be new or updated documentation for this change? (Be specific.)
Documentation team has already done their work.

## PR Checklist
- [x ] The JIRA ticket number and a short description is in the subject line
- [x ] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by a-pfeiffer** [comment]
@XiaoBarry @alihashmi-wh @fumanjie Hi All, please see the Jira ticket for a lot of information about testing,  I suspect many of my tickets for deprecating fields will follow this strategy.

**Comment by XiaoBarry** [comment]
@a-pfeiffer the code changes and test notebook look great! Thank you! One small suggestion I have is that in the your test notebook cmd 6 print output, I noticed that before changes were applied, the COPAY_WVD_IND was in the list 'upper' (,upper(a.COPAY_WVD_IND) as copay_wvd_ind). Now it is added to the list 'cleanser' to be set as null. We can remove it from the 'upper' list, as the two lists should be mutually exclusive. We don't want 'upper' to execute inadvertently.

**Review by XiaoBarry — APPROVED** [review]
All looks good to me! Thanks.

**Comment by a-pfeiffer** [comment]
updated testing after Main->CCB1 merge, and CCB1 -> This branch merge.     No issues found.   https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1617803729690761

**Pull request merged**
