### PR TITLE
MACDC-4594 Restore CSO Handling for MCP

### PR DESCRIPTION
**Pull request by rmNewnham**
## What is this?
This is for MACDC-4594 MCP record counts different between python and prod when there are records with older tmsis_rptg_prd values

## How would you classify this change (feature, bug, maintenance, etc.)?
Bug

## How did I test this (if code change)?
Using Oct 2022 data for states 06, 20, and 97, compared production data against python data to show original defect, state 07 had rows in py but not in production. Then reran MCP with fixed code(tst_macdc_4594) and compared py fix to prod and showed the results were the same. Done in notebook tst_macdc_4594.

## Issues Encountered

*Optional section to include any challenges encountered, options considered, and the approach chosen.*

## PR Checklist
- [x] Is the issue number and a short description in the subject line?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works -- in Databricks
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

_Credit to TMSIS PR template and https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects_

### CODE REVIEW

**Comment by rmNewnham** [comment]
Notebook for running fixed MCP wheel https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3674070/command/3674082

Notebook for testing https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3640187/command/3647541

**Comment by C1KB-tensileai** [comment]
Hi @rmNewnham, following up on your question regarding version number in `__init__.py`. Our intent is to align wheel file versions with each sprint (so today ends PI01.5), mainly so we have the ability to easily roll back changes. The same could be accomplished by building off a previous commit, I'll raise a PR this evening to advance to the correct sprint (heading into PI01.IP next week).

Here's the PI schedule for reference:
(https://cms-dataconnect.atlassian.net/wiki/spaces/DW/pages/25073057803/PI+Hub)

**Review by C1KB-tensileai — APPROVED** [review]
Thanks @rmNewnham, looks good. Just a FYI, on DataConnect whoever raises PRs typically merges after they are approved.

**Review by FICU-tensileai — APPROVED** [review]
Looks good. Matt, you can go ahead and merge when you're ready and feel free to delete the branch.

**Pull request merged**
